### ISSUE TITLE
Problem mit speichern der Datenbank

### ISSUE THREAD

**Issue by grobbbbbbbyy** [polarwinkel/GradeMan2#1]
Hallo!

Ich bin voller Begeisterung auf Grademan2 gestoßen und habe es zum Laufen gebracht. Ich würde es gerne im nächsten Schuljahr produktiv nutzen, daher teste ich mich durch die Funktionen. Leider bekomme ich die folgende Fehlermeldung, wenn ich versuche eine neue Datenbank abzuspeichern.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/oberstudienrat/GradeMan2/app.py", line 270, in updateSettings
    settings.set(setnew, setfile)
  File "/home/oberstudienrat/GradeMan2/modules/settingsio.py", line 41, in set
    if setnew['password']!= '':
KeyError: 'password'

**Comment by polarwinkel** [comment]
Moin,
danke für den report!

Der Fehler bei dir ist vermutlich ein Zwischen-Entwicklungsstand der letzten Tage, er sollte mit dem aktuellen Stand auf GitHub eigentlich schon wieder weg sein. Daher close ich es mal, wenn es doch noch auftaucht bitte gerne wieder öffnen, dann schaue ich noch mal genauer.

Ich habe es bei mir schon dieses Schuljahr im Produktiveinsatz, aber bei noch sehr aktiver Entwicklung, bis zum Sommer werde ich ein stable release veröffentlichen.

Aktuell würde ich empfehlen, je nach Kenntnisstand, per git Aktualisierungen vor zu nehmen immer wenn ich ein paar Tage _nichts_ neues gepushed habe, dann scheint es bei mir gut zu laufen. Bis zum ersten stable pushe ich aktuell aus Bequemlichkeit noch immer in den master-branch.
Aber der aktuelle Stand heute ist auch recht stable, zwischendurch kann es aktuell immer mal sein dass Fehler kurz auftreten.

**Comment by grobbbbbbbyy** [comment]
Vielen Dank für die Rückmeldung!

Funktioniert jetzt wieder!
